### ISSUE TITLE
[Bug] Using the HuskhomesSign when the player is already in Huskhome teleport warmup time throws an unexpected error

### ISSUE THREAD

**Issue by EnchantedHay** [MagmaBlock/HuskHomesSign#2]
To reproduce:
 - Huskhomes config: teleport_warmup_time > 0
 - Use a HuskhomesSign / Use a Huskhome teleport command
 - Use a HuskhomesSign again during warm-up time

→ 'Error happened while teleporting you to this destination. Error details have been printed to the console'
→ Console: Error:AlreadyWarmUp

**Comment by MagmaBlock** [comment]
Fixed in `1.2.0`.
